/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c17444b74e9586e28a0aa60ee4c2fe28)
interface __BaseEnv_Env {
	GITHUB_OWNER: "mtpark-ai";
	GITHUB_REPO: "agent-tasks";
	ISSUE_LABELS: "status:needs-triage,agent:unassigned,type:raw,source:external";
	MAX_BODY_BYTES: "50000";
	AUTH_TOKEN: string;
	GITHUB_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_OWNER" | "GITHUB_REPO" | "ISSUE_LABELS" | "MAX_BODY_BYTES" | "AUTH_TOKEN" | "GITHUB_TOKEN">> {}
}
