/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false` (hash: 4ca5e401891df94ac1e82a61133341b9)
interface __BaseEnv_Env {
	GITHUB_OWNER: string;
	GITHUB_REPO: string;
	ISSUE_LABELS: string;
	MAX_BODY_BYTES: string;
	AUTH_TOKEN: string;
	GITHUB_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_OWNER" | "GITHUB_REPO" | "ISSUE_LABELS" | "MAX_BODY_BYTES" | "AUTH_TOKEN" | "GITHUB_TOKEN">> {}
}
