/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 3eb1e480700e073a3e6e509fdcb2a4c2)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	APP_VERSION: string;
	GITHUB_OWNER: string;
	GITHUB_REPO: string;
	ISSUE_LABELS: string;
	MAX_BODY_BYTES: string;
	SHORTCUT_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_VERSION" | "GITHUB_OWNER" | "GITHUB_REPO" | "ISSUE_LABELS" | "MAX_BODY_BYTES" | "SHORTCUT_URL">> {}
}
